msg: hello dev
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
security:
  oauth2:
    resource:
      userInfoUri: "http://localhost:8762/user"
spring:
  zipkin:
    base-url: "http://localhost:9411"

