logging:
    level:
        com:
            operr: INFO
server:
    port: 9093
spring:
    datasource:
        password: password
        url: jdbc:mysql://192.168.10.59:3306/operr_v3_prod?autoReconnect=true&useSSL=false
        username: root
    elastic:
        url: ''
    redis:
        database: 0
        host: localhost
        password: ''
        port: 6379
