APP_ENV: local
AWS_KEY: AKIAJYPCBKFMAJOAOUEA
AWS_SECRET: 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
AWS_S3_URL: https://s3.amazonaws.com/operr-3.0.0/
AWS_S3_BUCKET: operr-3.0.0
AWS_S3_BASE_FOLDER: dev/
AWS_S3_REGION: us-east-1
AWS_S3_ADMIN_IMG_FOLDER: admin/
AWS_S3_DRIVER_IMG_FOLDER: driver/
AWS_S3_USER_IMG_FOLDER: user/
GOOGLE_API_KEY: AIzaSyAi49lL84Iw110hJppU4AyXwb7OmGyFvOU
FLIGHTSTATS_APP_ID: 1386ce8c
FLIGHTSTATS_APP_KEY: 0f0118464dfced76875b98775d6a8a99
TWILIO_ACCOUNT_SID: AC667a11ac090599737f807bc4b91a5133
TWILIO_AUTH_TOKEN: 6f6a4b9394901a02bd28bc8d43d302d1
TWILIO_FROM :  +19179354220
WEBSITE_BASE_URL: https://platform.ecarride.com/operr_dev
AUTHORIZE_NET_API_LOGIN_ID: 6m7C7MyhLS
AUTHORIZE_NET_TRANSACTION_KEY: 32NS92zg96Ar436M
logging:
    level:
        com:
            operr: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

operr:
    logging:
        logstash:
            enabled: true
            host: 192.168.130.66
            port: 9067
            queue-size: 512
server:
    port: 8080
spring:
    devtools:
        restart: enabled
    datasource:
        password: 0p8rr@SQL
        url: jdbc:mysql://69.18.194.204:3306/operr_v3_dev_sp1?characterEncoding=UTF-8
        username: root
    jpa:
        show-sql: true
    logging:
        level:
            org:
                hibernate:
                    SQL: debug
    redis:
        database: 0
        host: 69.18.194.202
        password: FYeuFEQVtshmZrXDCdVZNrGsSz7S8bz8
        port: 6379

zuul:
    routes:
          operr-v3-base:
                path: /base/**
                url: http://localhost:9070/
          operr-v3-core:
                path: /core/**
                url: http://localhost:9071/
          operr-v3-customer:
                path: /customer/**
                url: http://localhost:9072/
          operr-v3-driver:
                path: /driver/**
                url: http://localhost:9073/
          operr-v3-message:
                path: /message/**
                url: http://localhost:9074/
          operr-v3-schedule:
                path: /compliance/**
                url: http://localhost:9075/
          operr-v3-billing:
                path: /billing/**
                url: http://localhost:8766/
          operr-v3-sso:
                path: /sso/**
                url: http://localhost:8088/
                
#below configure is for spring boot admin
management.security.enabled: false
